name: CI Pipeline - Build Stage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go make
      - name: Build program
        run: |
          make build
          mkdir -p usr/bin
          cp factor_app usr/bin/
          chmod +x usr/bin/factor_app
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-program
          path: usr/bin/factor_app
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-program
          path: ./usr/bin
      - run: chmod +x ./usr/bin/factor_app
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run tests
        run: |
          cd cicd
  package:
    needs: [build, test]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: built-program
          path: ./usr/bin
      - name: Build .deb package
        run: |
          mkdir -p DEBIAN
          cp control DEBIAN/control
          dpkg-deb --build . go.deb
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: 'go.deb'
          retention-days: 1
